tooltip
js-tasks-ru/js-20210427_levita pull request #5
Opened 2021-05-20 18:37 UTC by Levitinn

2021-05-20 18:37 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 06-events-practice/2-tooltip/index.spec.js — изменен
```

2021-05-21 12:56 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        const divs = document.querySelectorAll('[data-tooltip]');
как ранее написал в чате - не следует привязываться к выборке элементов в этом методе. Элементы могут добавляться и удаляться динамически.

2021-05-21 12:56 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +            item.addEventListener('mousemove', ev => this.moveTooltip(ev))
этот обработчик следует навесить при наведении на элемент

2021-05-21 12:56 UTC, dosandk commented on 06-events-practice/2-tooltip/style.css
> +  pointer-events: none;
good 👍

2021-05-21 12:57 UTC, dosandk requested changes
следует внести правки согласно комментариев

2021-05-24 11:38 UTC, dosandk approved these changes
good 👍

2021-05-24 11:39 UTC, merged